// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63z2Q72BznQhyXK5nojT8TxJN9SrWB40',
    appId: '1:563601735159:web:6e1f6f85d4092a35ab42f2',
    messagingSenderId: '563601735159',
    projectId: 'jom-recycle-backend',
    authDomain: 'jom-recycle-backend.firebaseapp.com',
    storageBucket: 'jom-recycle-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnZnqRXuhTt_dlGbZkXp7oKujvHIO3Yk',
    appId: '1:563601735159:android:7793fc6bbd8cb38dab42f2',
    messagingSenderId: '563601735159',
    projectId: 'jom-recycle-backend',
    storageBucket: 'jom-recycle-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaSQg2pWKjqwEFf9EpBIx5W21wYMKUerE',
    appId: '1:563601735159:ios:f2d6c39eb780ee84ab42f2',
    messagingSenderId: '563601735159',
    projectId: 'jom-recycle-backend',
    storageBucket: 'jom-recycle-backend.firebasestorage.app',
    iosBundleId: 'com.example.jomRecycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaSQg2pWKjqwEFf9EpBIx5W21wYMKUerE',
    appId: '1:563601735159:ios:f2d6c39eb780ee84ab42f2',
    messagingSenderId: '563601735159',
    projectId: 'jom-recycle-backend',
    storageBucket: 'jom-recycle-backend.firebasestorage.app',
    iosBundleId: 'com.example.jomRecycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC63z2Q72BznQhyXK5nojT8TxJN9SrWB40',
    appId: '1:563601735159:web:e62abc6c0686794bab42f2',
    messagingSenderId: '563601735159',
    projectId: 'jom-recycle-backend',
    authDomain: 'jom-recycle-backend.firebaseapp.com',
    storageBucket: 'jom-recycle-backend.firebasestorage.app',
  );

}